import {
  Bell,
  Bookmark,
  Camera,
  Compass,
  Disc3,
  Earth,
  Flame,
  Gem,
  Globe,
  Headphones,
  Heart,
  Layers,
  MapPin,
  Mic2,
  Music,
  Music2,
  Navigation,
  Palette,
  PartyPopper,
  Plane,
  Radio,
  Search,
  Share2,
  Sparkles,
  Star,
  Ticket,
  Trophy,
  Users,
  Zap,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

/**
 * Icônes lucide proposées dans l'admin. Les mêmes noms existent dans
 * lucide-react (web) et lucide-react-native (mobile) : l'onboarding mobile
 * peut donc les afficher telles quelles.
 */
export const ICON_CHOICES: { name: string; Icon: LucideIcon }[] = [
  { name: 'Globe', Icon: Globe },
  { name: 'Search', Icon: Search },
  { name: 'Heart', Icon: Heart },
  { name: 'Trophy', Icon: Trophy },
  { name: 'MapPin', Icon: MapPin },
  { name: 'Compass', Icon: Compass },
  { name: 'Sparkles', Icon: Sparkles },
  { name: 'Star', Icon: Star },
  { name: 'Music', Icon: Music },
  { name: 'Music2', Icon: Music2 },
  { name: 'Disc3', Icon: Disc3 },
  { name: 'Radio', Icon: Radio },
  { name: 'Mic2', Icon: Mic2 },
  { name: 'Headphones', Icon: Headphones },
  { name: 'Navigation', Icon: Navigation },
  { name: 'Earth', Icon: Earth },
  { name: 'Plane', Icon: Plane },
  { name: 'PartyPopper', Icon: PartyPopper },
  { name: 'Camera', Icon: Camera },
  { name: 'Users', Icon: Users },
  { name: 'Share2', Icon: Share2 },
  { name: 'Bell', Icon: Bell },
  { name: 'Zap', Icon: Zap },
  { name: 'Flame', Icon: Flame },
  { name: 'Bookmark', Icon: Bookmark },
  { name: 'Gem', Icon: Gem },
  { name: 'Palette', Icon: Palette },
  { name: 'Ticket', Icon: Ticket },
  { name: 'Layers', Icon: Layers },
]
